
export const AU_ADDRESS_REGEX =
/^(\S*\/)?(\S*)\s(\D*)\s(ACCESS|ALLEY|ALLEYWAY|AMBLE|ANCHORAGE|APPROACH|ARCADE|ARTERIAL|ARTERY|AVENUE|BANAN|BANK|BASIN|BAY|BEACH|BEND|BLOCK|BOARDWALK|BOULEVARD|BOULEVARDE|BOWL|BRACE|BRAE|BREAK|BRIDGE|BROADWAY|BROW|BYPASS|BYWAY|CANAL|CAUSEWAY|CENTRE|CENTREWAY|CHASE|CIRCLE|CIRCLET|CIRCUIT|CIRCUS|CLOSE|CLUSTER|COLONNADE|COMMON|CONCOURSE|CONNECTION|COPSE|CORNER|CORSO|COURSE|COURT|COURTYARD|COVE|CRESCENT|CREST|CROSS|CROSSING|CROSSROAD|CROSSWAY|CRUISEWAY|CUL-DE-SAC|CUTTING|DALE|DELL|DENE|DEVIATION|DIP|DISTRIBUTOR|DIVIDE|DOCK|DOMAIN|DRIVE|DRIVEWAY|EDGE|ELBOW|END|ENTRANCE|ESPLANADE|ESTATE|ESTUARY|EXPRESSWAY|EXTENSION|FAIRWAY|FIRE TRACK|FIREBREAK|FIRELINE|FIRETRACK|FIRETRAIL|FLAT|FOLLOW|FOOTWAY|FORD|FORESHORE|FORMATION|FREEWAY|FRONT|FRONTAGE|GAP|GARDEN|GARDENS|GATE|GATES|GATEWAY|GLADE|GLEN|GRANGE|GREEN|GROUND|GROVE|GULLY|HARBOUR|HEATH|HEIGHTS|HIGHROAD|HIGHWAY|HILL|HOLLOW|HUB|INTERCHANGE|INTERSECTION|JUNCTION|KEY|KEYS|LANDING|LANE|LANEWAY|LEES|LINE|LINK|LITTLE|LOOKOUT|LOOP|LOWER|MALL|MANOR|MEANDER|MEARS|MEW|MEWS|MILE|MOTORWAY|MOUNT|NOOK|OUTLET|OUTLOOK|PARADE|PARK|PARKLANDS|PARKWAY|PART|PASS|PASSAGE|PATH|PATHWAY|PIAZZA|PIER|PLACE|PLATEAU|PLAZA|POCKET|POINT|PORT|PORTAL|PROMENADE|PURSUIT|QUAD|QUADRANGLE|QUADRANT|QUAY|QUAYS|RAMBLE|RAMP|RANGE|REACH|RESERVE|REST|RETREAT|RETURN|RIDE|RIDGE|RIDGEWAY|RIGHT OF WAY|RING|RISE|RISING|RIVER|RIVERWAY|RIVIERA|ROAD|ROADS|ROADSIDE|ROADWAY|RONDE|ROSEBOWL|ROTARY|ROUND|ROUTE|ROW|RUE|RUN|SERVICE WAY|SHUNT|SIDING|SLOPE|SOUND|SPUR|SQUARE|STAIRS|STATE HIGHWAY|STEPS|STRAND|STREET|STREETS|STRIP|SUBWAY|TARN|TARNICE WAY|TERRACE|THOROUGHFARE|THROUGHWAY|TOLLWAY|TOP|TOR|TOWERS|TRACK|TRAIL|TRAILER|TRIANGLE|TRUNKWAY|TURN|TWIST|UNDERPASS|UPPER|VALE|VIADUCT|VIEW|VILLAS|VISTA|WADE|WALK|WALKWAY|WATERWAY|WAY|WHARF|WOODS|WYND|YARD)\s(\D*)\s(NSW|VIC|QLD|SA|WA|TAS|NT|ACT|OT)\s([0-9]{4})$/i;

export const ADDRESS_FORMAT = /^([a-zA-Z0-9]*[^unit]\s\s*\d[a-zA-Z0-9]*-*[a-zA-Z0-9]*)\s*([a-zA-Z0-9_ ]*)$/i;

export const AUSTRALIA_STATES = [
{ value: 'ACT', label: 'ACT' },
{ value: 'NSW', label: 'NSW' },
{ value: 'NT', label: 'NT' },
{ value: 'QLD', label: 'QLD' },
{ value: 'SA', label: 'SA' },
{ value: 'TAS', label: 'TAS' },
{ value: 'VIC', label: 'VIC' },
{ value: 'WA', label: 'WA' },
];

export const STREET_SUFFIX = [
{ value: 'Central', label: 'Central' },
{ value: 'Deviation', label: 'Deviation' },
{ value: 'East', label: 'East' },
{ value: 'Extension', label: 'Extension' },
{ value: 'Lower', label: 'Lower' },
{ value: 'Inner', label: 'Inner' },
{ value: 'Mall', label: 'Mall' },
{ value: 'North', label: 'North' },
{ value: 'North East', label: 'North East' },
{ value: 'North West', label: 'North West' },
{ value: 'Off', label: 'Off' },
{ value: 'On', label: 'On' },
{ value: 'Outer', label: 'Outer' },
{ value: 'Overpass', label: 'Overpass' },
{ value: 'South', label: 'South' },
{ value: 'South East', label: 'South East' },
{ value: 'South West', label: 'South West' },
{ value: 'Upper', label: 'Upper' },
{ value: 'West', label: 'West' },
];

export const STREET_TYPE: { value: string; label: string }[] = [
{ value: 'Access', label: 'Access' },
{ value: 'Alley', label: 'Alley' },
{ value: 'Alleyway', label: 'Alleyway' },
{ value: 'Amble', label: 'Amble' },
{ value: 'Anchorage', label: 'Anchorage' },
{ value: 'Approach', label: 'Approach' },
{ value: 'Arcade', label: 'Arcade' },
{ value: 'Arterial', label: 'Arterial' },
{ value: 'Artery', label: 'Artery' },
{ value: 'Avenue', label: 'Avenue' },
{ value: 'Banan', label: 'Banan' },
{ value: 'Bank', label: 'Bank' },
{ value: 'Basin', label: 'Basin' },
{ value: 'Bay', label: 'Bay' },
{ value: 'Beach', label: 'Beach' },
{ value: 'Bend', label: 'Bend' },
{ value: 'Block', label: 'Block' },
{ value: 'Boardwalk', label: 'Boardwalk' },
{ value: 'Boulevard', label: 'Boulevard' },
{ value: 'Boulevarde', label: 'Boulevarde' },
{ value: 'Bowl', label: 'Bowl' },
{ value: 'Brace', label: 'Brace' },
{ value: 'Brae', label: 'Brae' },
{ value: 'Break', label: 'Break' },
{ value: 'Bridge', label: 'Bridge' },
{ value: 'Broadway', label: 'Broadway' },
{ value: 'Brow', label: 'Brow' },
{ value: 'Bypass', label: 'Bypass' },
{ value: 'Byway', label: 'Byway' },
{ value: 'Canal', label: 'Canal' },
{ value: 'Causeway', label: 'Causeway' },
{ value: 'Centre', label: 'Centre' },
{ value: 'Centreway', label: 'Centreway' },
{ value: 'Chase', label: 'Chase' },
{ value: 'Circle', label: 'Circle' },
{ value: 'Circlet', label: 'Circlet' },
{ value: 'Circuit', label: 'Circuit' },
{ value: 'Circus', label: 'Circus' },
{ value: 'Close', label: 'Close' },
{ value: 'Cluster', label: 'Cluster' },
{ value: 'Colonnade', label: 'Colonnade' },
{ value: 'Common', label: 'Common' },
{ value: 'Concourse', label: 'Concourse' },
{ value: 'Connection', label: 'Connection' },
{ value: 'Copse', label: 'Copse' },
{ value: 'Corner', label: 'Corner' },
{ value: 'Corso', label: 'Corso' },
{ value: 'Course', label: 'Course' },
{ value: 'Court', label: 'Court' },
{ value: 'Courtyard', label: 'Courtyard' },
{ value: 'Cove', label: 'Cove' },
{ value: 'Crescent', label: 'Crescent' },
{ value: 'Crest', label: 'Crest' },
{ value: 'Cross', label: 'Cross' },
{ value: 'Crossing', label: 'Crossing' },
{ value: 'Crossroad', label: 'Crossroad' },
{ value: 'Crossway', label: 'Crossway' },
{ value: 'Cruiseway', label: 'Cruiseway' },
{ value: 'Cul-De-Sac', label: 'Cul-De-Sac' },
{ value: 'Cutting', label: 'Cutting' },
{ value: 'Dale', label: 'Dale' },
{ value: 'Dell', label: 'Dell' },
{ value: 'Dene', label: 'Dene' },
{ value: 'Deviation', label: 'Deviation' },
{ value: 'Dip', label: 'Dip' },
{ value: 'Distributor', label: 'Distributor' },
{ value: 'Divide', label: 'Divide' },
{ value: 'Dock', label: 'Dock' },
{ value: 'Domain', label: 'Domain' },
{ value: 'Drive', label: 'Drive' },
{ value: 'Driveway', label: 'Driveway' },
{ value: 'Edge', label: 'Edge' },
{ value: 'Elbow', label: 'Elbow' },
{ value: 'End', label: 'End' },
{ value: 'Entrance', label: 'Entrance' },
{ value: 'Esplanade', label: 'Esplanade' },
{ value: 'Estate', label: 'Estate' },
{ value: 'Estuary', label: 'Estuary' },
{ value: 'Expressway', label: 'Expressway' },
{ value: 'Extension', label: 'Extension' },
{ value: 'Fairway', label: 'Fairway' },
{ value: 'Fire Track', label: 'Fire Track' },
{ value: 'Firebreak', label: 'Firebreak' },
{ value: 'Fireline', label: 'Fireline' },
{ value: 'Firetrack', label: 'Firetrack' },
{ value: 'Firetrail', label: 'Firetrail' },
{ value: 'Flat', label: 'Flat' },
{ value: 'Follow', label: 'Follow' },
{ value: 'Footway', label: 'Footway' },
{ value: 'Ford', label: 'Ford' },
{ value: 'Foreshore', label: 'Foreshore' },
{ value: 'Formation', label: 'Formation' },
{ value: 'Freeway', label: 'Freeway' },
{ value: 'Front', label: 'Front' },
{ value: 'Frontage', label: 'Frontage' },
{ value: 'Gap', label: 'Gap' },
{ value: 'Garden', label: 'Garden' },
{ value: 'Gardens', label: 'Gardens' },
{ value: 'Gate', label: 'Gate' },
{ value: 'Gates', label: 'Gates' },
{ value: 'Gateway', label: 'Gateway' },
{ value: 'Glade', label: 'Glade' },
{ value: 'Glen', label: 'Glen' },
{ value: 'Grange', label: 'Grange' },
{ value: 'Green', label: 'Green' },
{ value: 'Ground', label: 'Ground' },
{ value: 'Grove', label: 'Grove' },
{ value: 'Gully', label: 'Gully' },
{ value: 'Harbour', label: 'Harbour' },
{ value: 'Heath', label: 'Heath' },
{ value: 'Heights', label: 'Heights' },
{ value: 'Highroad', label: 'Highroad' },
{ value: 'Highway', label: 'Highway' },
{ value: 'Hill', label: 'Hill' },
{ value: 'Hollow', label: 'Hollow' },
{ value: 'Hub', label: 'Hub' },
{ value: 'Interchange', label: 'Interchange' },
{ value: 'Intersection', label: 'Intersection' },
{ value: 'Junction', label: 'Junction' },
{ value: 'Key', label: 'Key' },
{ value: 'Keys', label: 'Keys' },
{ value: 'Landing', label: 'Landing' },
{ value: 'Lane', label: 'Lane' },
{ value: 'Laneway', label: 'Laneway' },
{ value: 'Lees', label: 'Lees' },
{ value: 'Line', label: 'Line' },
{ value: 'Link', label: 'Link' },
{ value: 'Little', label: 'Little' },
{ value: 'Lookout', label: 'Lookout' },
{ value: 'Loop', label: 'Loop' },
{ value: 'Lower', label: 'Lower' },
{ value: 'Mall', label: 'Mall' },
{ value: 'Manor', label: 'Manor' },
{ value: 'Meander', label: 'Meander' },
{ value: 'Mears', label: 'Mears' },
{ value: 'Mew', label: 'Mew' },
{ value: 'Mews', label: 'Mews' },
{ value: 'Mile', label: 'Mile' },
{ value: 'Motorway', label: 'Motorway' },
{ value: 'Mount', label: 'Mount' },
{ value: 'Nook', label: 'Nook' },
{ value: 'Outlet', label: 'Outlet' },
{ value: 'Outlook', label: 'Outlook' },
{ value: 'Parade', label: 'Parade' },
{ value: 'Park', label: 'Park' },
{ value: 'Parklands', label: 'Parklands' },
{ value: 'Parkway', label: 'Parkway' },
{ value: 'Part', label: 'Part' },
{ value: 'Pass', label: 'Pass' },
{ value: 'Passage', label: 'Passage' },
{ value: 'Path', label: 'Path' },
{ value: 'Pathway', label: 'Pathway' },
{ value: 'Piazza', label: 'Piazza' },
{ value: 'Pier', label: 'Pier' },
{ value: 'Place', label: 'Place' },
{ value: 'Plateau', label: 'Plateau' },
{ value: 'Plaza', label: 'Plaza' },
{ value: 'Pocket', label: 'Pocket' },
{ value: 'Point', label: 'Point' },
{ value: 'Port', label: 'Port' },
{ value: 'Portal', label: 'Portal' },
{ value: 'Promenade', label: 'Promenade' },
{ value: 'Pursuit', label: 'Pursuit' },
{ value: 'Quad', label: 'Quad' },
{ value: 'Quadrangle', label: 'Quadrangle' },
{ value: 'Quadrant', label: 'Quadrant' },
{ value: 'Quay', label: 'Quay' },
{ value: 'Quays', label: 'Quays' },
{ value: 'Ramble', label: 'Ramble' },
{ value: 'Ramp', label: 'Ramp' },
{ value: 'Range', label: 'Range' },
{ value: 'Reach', label: 'Reach' },
{ value: 'Reserve', label: 'Reserve' },
{ value: 'Rest', label: 'Rest' },
{ value: 'Retreat', label: 'Retreat' },
{ value: 'Return', label: 'Return' },
{ value: 'Ride', label: 'Ride' },
{ value: 'Ridge', label: 'Ridge' },
{ value: 'Ridgeway', label: 'Ridgeway' },
{ value: 'Right Of Way', label: 'Right Of Way' },
{ value: 'Ring', label: 'Ring' },
{ value: 'Rise', label: 'Rise' },
{ value: 'Rising', label: 'Rising' },
{ value: 'River', label: 'River' },
{ value: 'Riverway', label: 'Riverway' },
{ value: 'Riviera', label: 'Riviera' },
{ value: 'Road', label: 'Road' },
{ value: 'Roads', label: 'Roads' },
{ value: 'Roadside', label: 'Roadside' },
{ value: 'Roadway', label: 'Roadway' },
{ value: 'Ronde', label: 'Ronde' },
{ value: 'Rosebowl', label: 'Rosebowl' },
{ value: 'Rotary', label: 'Rotary' },
{ value: 'Round', label: 'Round' },
{ value: 'Route', label: 'Route' },
{ value: 'Row', label: 'Row' },
{ value: 'Rue', label: 'Rue' },
{ value: 'Run', label: 'Run' },
{ value: 'Service Way', label: 'Service Way' },
{ value: 'Shunt', label: 'Shunt' },
{ value: 'Siding', label: 'Siding' },
{ value: 'Slope', label: 'Slope' },
{ value: 'Sound', label: 'Sound' },
{ value: 'Spur', label: 'Spur' },
{ value: 'Square', label: 'Square' },
{ value: 'Stairs', label: 'Stairs' },
{ value: 'State Highway', label: 'State Highway' },
{ value: 'Steps', label: 'Steps' },
{ value: 'Strand', label: 'Strand' },
{ value: 'Street', label: 'Street' },
{ value: 'Streets', label: 'Streets' },
{ value: 'Strip', label: 'Strip' },
{ value: 'Subway', label: 'Subway' },
{ value: 'Tarn', label: 'Tarn' },
{ value: 'Tarnice Way', label: 'Tarnice Way' },
{ value: 'Terrace', label: 'Terrace' },
{ value: 'Thoroughfare', label: 'Thoroughfare' },
{ value: 'Throughway', label: 'Throughway' },
{ value: 'Tollway', label: 'Tollway' },
{ value: 'Top', label: 'Top' },
{ value: 'Tor', label: 'Tor' },
{ value: 'Towers', label: 'Towers' },
{ value: 'Track', label: 'Track' },
{ value: 'Trail', label: 'Trail' },
{ value: 'Trailer', label: 'Trailer' },
{ value: 'Triangle', label: 'Triangle' },
{ value: 'Trunkway', label: 'Trunkway' },
{ value: 'Turn', label: 'Turn' },
{ value: 'Twist', label: 'Twist' },
{ value: 'Underpass', label: 'Underpass' },
{ value: 'Upper', label: 'Upper' },
{ value: 'Vale', label: 'Vale' },
{ value: 'Viaduct', label: 'Viaduct' },
{ value: 'View', label: 'View' },
{ value: 'Villas', label: 'Villas' },
{ value: 'Vista', label: 'Vista' },
{ value: 'Wade', label: 'Wade' },
{ value: 'Walk', label: 'Walk' },
{ value: 'Walkway', label: 'Walkway' },
{ value: 'Waterway', label: 'Waterway' },
{ value: 'Way', label: 'Way' },
{ value: 'Wharf', label: 'Wharf' },
{ value: 'Woods', label: 'Woods' },
{ value: 'Wynd', label: 'Wynd' },
{ value: 'Yard', label: 'Yard' },
];

export const COUNTRY = [
{ label: 'Afghanistan', value: 'Afghanistan' },
{ label: 'Albania', value: 'Albania' },
{ label: 'Algeria', value: 'Algeria' },
{ label: 'American Samoa', value: 'American Samoa' },
{ label: 'Andorra', value: 'Andorra' },
{ label: 'Angola', value: 'Angola' },
{ label: 'Anguilla', value: 'Anguilla' },
{ label: 'Antarctica', value: 'Antarctica' },
{ label: 'Antigua And Barbuda', value: 'Antigua And Barbuda' },
{ label: 'Argentina', value: 'Argentina' },
{ label: 'Armenia', value: 'Armenia' },
{ label: 'Aruba', value: 'Aruba' },
{ label: 'Australia', value: 'Australia' },
{ label: 'Austria', value: 'Austria' },
{ label: 'Azerbaijan', value: 'Azerbaijan' },
{ label: 'Bahamas', value: 'Bahamas' },
{ label: 'Bahrain', value: 'Bahrain' },
{ label: 'Bangladesh', value: 'Bangladesh' },
{ label: 'Barbados', value: 'Barbados' },
{ label: 'Belarus', value: 'Belarus' },
{ label: 'Belgium', value: 'Belgium' },
{ label: 'Belize', value: 'Belize' },
{ label: 'Benin', value: 'Benin' },
{ label: 'Bermuda', value: 'Bermuda' },
{ label: 'Bhutan', value: 'Bhutan' },
{ label: 'Bolivia', value: 'Bolivia' },
{ label: 'Bosnia And Herzegovina', value: 'Bosnia And Herzegovina' },
{ label: 'Botswana', value: 'Botswana' },
{ label: 'Bouvet Island', value: 'Bouvet Island' },
{ label: 'Brazil', value: 'Brazil' },
{ label: 'British Indian Ocean Territory', value: 'British Indian Ocean Territory' },
{ label: 'Brunei Darussalam', value: 'Brunei Darussalam' },
{ label: 'Bulgaria', value: 'Bulgaria' },
{ label: 'Burkina Faso', value: 'Burkina Faso' },
{ label: 'Burundi', value: 'Burundi' },
{ label: 'Cambodia', value: 'Cambodia' },
{ label: 'Cameroon', value: 'Cameroon' },
{ label: 'Canada', value: 'Canada' },
{ label: 'Cape Verde', value: 'Cape Verde' },
{ label: 'Cayman Islands', value: 'Cayman Islands' },
{ label: 'Central African Republic', value: 'Central African Republic' },
{ label: 'Chad', value: 'Chad' },
{ label: 'Chile', value: 'Chile' },
{ label: 'China', value: 'China' },
{ label: 'Christmas Island', value: 'Christmas Island' },
{ label: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
{ label: 'Colombia', value: 'Colombia' },
{ label: 'Comoros', value: 'Comoros' },
{ label: "Democratic People's Republic of Korea", value: "Democratic People's Republic of Korea" },
{ label: 'Democratic Republic Of The Congo', value: 'Democratic Republic Of The Congo' },
{ label: 'Cook Islands', value: 'Cook Islands' },
{ label: 'Costa Rica', value: 'Costa Rica' },
{ label: "Cote D'ivoire", value: "Cote D'ivoire" },
{ label: 'Croatia', value: 'Croatia' },
{ label: 'Cuba', value: 'Cuba' },
{ label: 'Cyprus', value: 'Cyprus' },
{ label: 'Czech Republic', value: 'Czech Republic' },
{ label: 'Denmark', value: 'Denmark' },
{ label: 'Djibouti', value: 'Djibouti' },
{ label: 'Dominica', value: 'Dominica' },
{ label: 'Dominican Republic', value: 'Dominican Republic' },
{ label: 'East Timor', value: 'East Timor' },
{ label: 'Ecuador', value: 'Ecuador' },
{ label: 'Egypt', value: 'Egypt' },
{ label: 'El Salvador', value: 'El Salvador' },
{ label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
{ label: 'Eritrea', value: 'Eritrea' },
{ label: 'Estonia', value: 'Estonia' },
{ label: 'Ethiopia', value: 'Ethiopia' },
{ label: 'Falkland Islands', value: 'Falkland Islands' },
{ label: 'Faroe Islands', value: 'Faroe Islands' },
{ label: 'Fiji', value: 'Fiji' },
{ label: 'Finland', value: 'Finland' },
{ label: 'France', value: 'France' },
{ label: 'French Guiana', value: 'French Guiana' },
{ label: 'French Polynesia', value: 'French Polynesia' },
{ label: 'French Southern Territories', value: 'French Southern Territories' },
{ label: 'Gabon', value: 'Gabon' },
{ label: 'Gambia', value: 'Gambia' },
{ label: 'Georgia', value: 'Georgia' },
{ label: 'Germany', value: 'Germany' },
{ label: 'Ghana', value: 'Ghana' },
{ label: 'Gibraltar', value: 'Gibraltar' },
{ label: 'Greece', value: 'Greece' },
{ label: 'Greenland', value: 'Greenland' },
{ label: 'Grenada', value: 'Grenada' },
{ label: 'Guadeloupe', value: 'Guadeloupe' },
{ label: 'Guam', value: 'Guam' },
{ label: 'Guatemala', value: 'Guatemala' },
{ label: 'Guinea', value: 'Guinea' },
{ label: 'Guinea-bissau', value: 'Guinea-bissau' },
{ label: 'Guyana', value: 'Guyana' },
{ label: 'Haiti', value: 'Haiti' },
{ label: 'Heard Island And Mcdonald Islands', value: 'Heard Island And Mcdonald Islands' },
{ label: 'Holy See (Vatican City State)', value: 'Holy See (Vatican City State)' },
{ label: 'Honduras', value: 'Honduras' },
{ label: 'Hong Kong', value: 'Hong Kong' },
{ label: 'Hungary', value: 'Hungary' },
{ label: 'Iceland', value: 'Iceland' },
{ label: 'India', value: 'India' },
{ label: 'Indonesia', value: 'Indonesia' },
{ label: 'Iran', value: 'Iran' },
{ label: 'Iraq', value: 'Iraq' },
{ label: 'Ireland', value: 'Ireland' },
{ label: 'Israel', value: 'Israel' },
{ label: 'Italy', value: 'Italy' },
{ label: 'Jamaica', value: 'Jamaica' },
{ label: 'Japan', value: 'Japan' },
{ label: 'Jordan', value: 'Jordan' },
{ label: 'Kazakstan', value: 'Kazakstan' },
{ label: 'Kenya', value: 'Kenya' },
{ label: 'Kiribati', value: 'Kiribati' },
{ label: 'Kosovo', value: 'Kosovo' },
{ label: 'Kuwait', value: 'Kuwait' },
{ label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
{ label: 'Laos', value: 'Laos' },
{ label: 'Latvia', value: 'Latvia' },
{ label: 'Lebanon', value: 'Lebanon' },
{ label: 'Lesotho', value: 'Lesotho' },
{ label: 'Liberia', value: 'Liberia' },
{ label: 'Libyan Arab Jamahiriya', value: 'Libyan Arab Jamahiriya' },
{ label: 'Liechtenstein', value: 'Liechtenstein' },
{ label: 'Lithuania', value: 'Lithuania' },
{ label: 'Luxembourg', value: 'Luxembourg' },
{ label: 'Macau', value: 'Macau' },
{ label: 'Macedonia', value: 'Macedonia' },
{ label: 'Madagascar', value: 'Madagascar' },
{ label: 'Malawi', value: 'Malawi' },
{ label: 'Malaysia', value: 'Malaysia' },
{ label: 'Maldives', value: 'Maldives' },
{ label: 'Mali', value: 'Mali' },
{ label: 'Malta', value: 'Malta' },
{ label: 'Marshall Islands', value: 'Marshall Islands' },
{ label: 'Martinique', value: 'Martinique' },
{ label: 'Mauritania', value: 'Mauritania' },
{ label: 'Mauritius', value: 'Mauritius' },
{ label: 'Mayotte', value: 'Mayotte' },
{ label: 'Mexico', value: 'Mexico' },
{ label: 'Federated States Of Micronesia', value: 'Federated States Of Micronesia' },
{ label: 'Republic Of Moldova', value: 'Republic Of Moldova' },
{ label: 'Monaco', value: 'Monaco' },
{ label: 'Mongolia', value: 'Mongolia' },
{ label: 'Montserrat', value: 'Montserrat' },
{ label: 'Montenegro', value: 'Montenegro' },
{ label: 'Morocco', value: 'Morocco' },
{ label: 'Mozambique', value: 'Mozambique' },
{ label: 'Myanmar', value: 'Myanmar' },
{ label: 'Namibia', value: 'Namibia' },
{ label: 'Nauru', value: 'Nauru' },
{ label: 'Nepal', value: 'Nepal' },
{ label: 'Netherlands', value: 'Netherlands' },
{ label: 'Netherlands Antilles', value: 'Netherlands Antilles' },
{ label: 'New Caledonia', value: 'New Caledonia' },
{ label: 'New Zealand', value: 'New Zealand' },
{ label: 'Nicaragua', value: 'Nicaragua' },
{ label: 'Niger', value: 'Niger' },
{ label: 'Nigeria', value: 'Nigeria' },
{ label: 'Niue', value: 'Niue' },
{ label: 'Norfolk Island', value: 'Norfolk Island' },
{ label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
{ label: 'Norway', value: 'Norway' },
{ label: 'Oman', value: 'Oman' },
{ label: 'Pakistan', value: 'Pakistan' },
{ label: 'Palau', value: 'Palau' },
{ label: 'Palestinian Territory', value: 'Palestinian Territory' },
{ label: 'Panama', value: 'Panama' },
{ label: 'Papua New Guinea', value: 'Papua New Guinea' },
{ label: 'Paraguay', value: 'Paraguay' },
{ label: 'Peru', value: 'Peru' },
{ label: 'Philippines', value: 'Philippines' },
{ label: 'Pitcairn', value: 'Pitcairn' },
{ label: 'Poland', value: 'Poland' },
{ label: 'Portugal', value: 'Portugal' },
{ label: 'Puerto Rico', value: 'Puerto Rico' },
{ label: 'Qatar', value: 'Qatar' },
{ label: 'Romania', value: 'Romania' },
{ label: 'Russian Federation', value: 'Russian Federation' },
{ label: 'Rwanda', value: 'Rwanda' },
{ label: 'Saint Helena', value: 'Saint Helena' },
{ label: 'Saint Kitts And Nevis', value: 'Saint Kitts And Nevis' },
{ label: 'Saint Lucia', value: 'Saint Lucia' },
{ label: 'Saint Pierre And Miquelon', value: 'Saint Pierre And Miquelon' },
{ label: 'Saint Vincent And The Grenadines', value: 'Saint Vincent And The Grenadines' },
{ label: 'Samoa', value: 'Samoa' },
{ label: 'San Marino', value: 'San Marino' },
{ label: 'Sao Tome And Principe', value: 'Sao Tome And Principe' },
{ label: 'Saudi Arabia', value: 'Saudi Arabia' },
{ label: 'Senegal', value: 'Senegal' },
{ label: 'Serbia', value: 'Serbia' },
{ label: 'Seychelles', value: 'Seychelles' },
{ label: 'Sierra Leone', value: 'Sierra Leone' },
{ label: 'Singapore', value: 'Singapore' },
{ label: 'Slovakia', value: 'Slovakia' },
{ label: 'Slovenia', value: 'Slovenia' },
{ label: 'Solomon Islands', value: 'Solomon Islands' },
{ label: 'Somalia', value: 'Somalia' },
{ label: 'South Africa', value: 'South Africa' },
{ label: 'South Georgia And The South Sandwich Islands', value: 'South Georgia And The South Sandwich Islands' },
{ label: 'The Republic of South Korea', value: 'The Republic of South Korea' },
{ label: 'Spain', value: 'Spain' },
{ label: 'Sri Lanka', value: 'Sri Lanka' },
{ label: 'Sudan', value: 'Sudan' },
{ label: 'Suriname', value: 'Suriname' },
{ label: 'Svalbard And Jan Mayen', value: 'Svalbard And Jan Mayen' },
{ label: 'Swaziland', value: 'Swaziland' },
{ label: 'Sweden', value: 'Sweden' },
{ label: 'Switzerland', value: 'Switzerland' },
{ label: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
{ label: 'Taiwan', value: 'Taiwan' },
{ label: 'Tajikistan', value: 'Tajikistan' },
{ label: 'Tanzania', value: 'Tanzania' },
{ label: 'Thailand', value: 'Thailand' },
{ label: 'Togo', value: 'Togo' },
{ label: 'Tokelau', value: 'Tokelau' },
{ label: 'Tonga', value: 'Tonga' },
{ label: 'Trinidad And Tobago', value: 'Trinidad And Tobago' },
{ label: 'Tunisia', value: 'Tunisia' },
{ label: 'Turkey', value: 'Turkey' },
{ label: 'Turkmenistan', value: 'Turkmenistan' },
{ label: 'Turks And Caicos Islands', value: 'Turks And Caicos Islands' },
{ label: 'Tuvalu', value: 'Tuvalu' },
{ label: 'Uganda', value: 'Uganda' },
{ label: 'Ukraine', value: 'Ukraine' },
{ label: 'United Arab Emirates', value: 'United Arab Emirates' },
{ label: 'United Kingdom', value: 'United Kingdom' },
{ label: 'United States of America', value: 'United States of America' },
{ label: 'United States Minor Outlying Islands', value: 'United States Minor Outlying Islands' },
{ label: 'Uruguay', value: 'Uruguay' },
{ label: 'Uzbekistan', value: 'Uzbekistan' },
{ label: 'Vanuatu', value: 'Vanuatu' },
{ label: 'Venezuela', value: 'Venezuela' },
{ label: 'Vietnam', value: 'Vietnam' },
{ label: 'British Virgin Islands', value: 'British Virgin Islands' },
{ label: 'US Virgin Islands', value: 'US Virgin Islands' },
{ label: 'Wallis And Futuna', value: 'Wallis And Futuna' },
{ label: 'Western Sahara', value: 'Western Sahara' },
{ label: 'Yemen', value: 'Yemen' },
{ label: 'Zambia', value: 'Zambia' },
{ label: 'Zimbabwe', value: 'Zimbabwe' },
];

export const STREET_SUFFIX_MAPPING: { [key: string]: string } = {
CN: 'Central',
CENTRAL: 'Central',
E: 'East',
EAST: 'East',
EX: 'Extension',
EXTENSION: 'Extension',
LOWER: 'Lower',
LR: 'Lower',
N: 'North',
NORTH: 'North',
NTH: 'North',
NE: 'North',
'NORTH EAST': 'North East',
'NORTH WEST': 'North West',
NW: 'North',
S: 'South',
SOUTH: 'South',
STH: 'South',
SE: 'South East',
'SOUTH EAST': 'South East',
'SOUTH WEST': 'South West',
SW: 'South West',
UP: 'Upper',
UPPER: 'Upper',
W: 'West',
WEST: 'West',
};

export const STREET_TYPE_MAPPING: { [key: string]: string } = {
ACCESS: 'Access',
ACCS: 'Access',
ALLEY: 'Alley',
ALLEYWAY: 'Alleyway',
ALLY: 'Alleyway',
AMBLE: 'Amble',
AMBL: 'Amble',
ANCHORAGE: 'Anchorage',
ANCG: 'Anchorage',
APPROACH: 'Approach',
APP: 'Approach',
ARCADE: 'Arcade',
ARC: 'Arcade',
ARTERY: 'Artery',
ART: 'Artery',
AVENUE: 'Avenue',
AV: 'Avenue',
AVE: 'Avenue',
AVEN: 'Avenue',
AVN: 'Avenue',
BASIN: 'Basin',
BASN: 'Basin',
BEACH: 'Beach',
BCH: 'Beach',
BRIDGE: 'Bridge',
BDGE: 'Bridge',
BROADWAY: 'Broadway',
BDWY: 'Broadway',
BEND: 'Bend',
BLOCK: 'Block',
BLK: 'Block',
BRAE: 'Brae',
BRACE: 'Brace',
BRCE: 'Brace',
BREAK: 'Break',
BRK: 'Break',
BROW: 'Brow',
BOULEVARD: 'Boulevard',
BOULEVARDE: 'Boulevard',
BLV: 'Boulevard',
BLVD: 'Boulevard',
BOUL: 'Boulevard',
BVARD: 'Boulevard',
BVD: 'Boulevard',
BYPASS: 'Bypass',
BYPA: 'Bypass',
BYWAY: 'Byway',
BYWY: 'Byway',
CAUSEWAY: 'Causeway',
CAUS: 'Causeway',
CIRCUIT: 'Circuit',
CCT: 'Circuit',
CRCT: 'Circuit',
'CUL-DE-SAC': 'Cul-de-sac',
CDS: 'Cul-de-sac',
CHASE: 'Chase',
CH: 'Chase',
CIRCLE: 'Circle',
CIR: 'Circle',
CLOSE: 'Close',
CL: 'Close',
CLOS: 'Close',
CLS: 'Close',
CLSE: 'Close',
COLONNADE: 'Colonnade',
CLDE: 'Colonnade',
CIRCLET: 'Circlet',
CLT: 'Circlet',
COMMON: 'Common',
CMMN: 'Common',
CORNER: 'Corner',
CNR: 'Corner',
CENTREWAY: 'Centreway',
CNWY: 'Centreway',
CONCOURSE: 'Concourse',
CON: 'Concourse',
COVE: 'Cove',
CROSSWAY: 'Crossway',
COWY: 'Crossway',
COPSE: 'Copse',
CPS: 'Copse',
CIRCUS: 'Circus',
CRCS: 'Circus',
CROSSROAD: 'Crossroad',
CRD: 'Crossroad',
CRESCENT: 'Crescent',
CR: 'Crescent',
CRES: 'Crescent',
CRS: 'Crescent',
CROSSING: 'Crossing',
CRSG: 'Crossing',
CROSS: 'Cross',
CRSS: 'Cross',
CREST: 'Crest',
CRST: 'Crest',
CORSO: 'Corso',
CSO: 'Corso',
COURT: 'Court',
CRT: 'Court',
CT: 'Court',
CENTRE: 'Centre',
CTR: 'Centre',
CUTTING: 'Cutting',
CTTG: 'Cutting',
COURTYARD: 'Courtyard',
CTYD: 'Courtyard',
CRUISEWAY: 'Cruiseway',
CUWY: 'Cruiseway',
DALE: 'Dale',
DELL: 'Dell',
DEVIATION: 'Deviation',
DEVN: 'Deviation',
DIP: 'Dip',
DRIVE: 'Drive',
DR: 'Drive',
DRV: 'Drive',
DVE: 'Drive',
DRIVEWAY: 'Driveway',
DRWY: 'Driveway',
DISTRIBUTOR: 'Distributor',
DSTR: 'Distributor',
EDGE: 'Edge',
ELBOW: 'Elbow',
ELB: 'Elbow',
END: 'End',
ENTRANCE: 'Entrance',
ENT: 'Entrance',
ESPLANADE: 'Esplanade',
ESP: 'Esplanade',
ESPL: 'Esplanade',
ESTATE: 'Estate',
EST: 'Estate',
EXPRESSWAY: 'Expressway',
EXP: 'Expressway',
EXWY: 'Expressway',
EXTENSION: 'Extension',
EXTN: 'Extension',
FAIRWAY: 'Fairway',
FAWY: 'Fairway',
FIRETRAIL: 'Firetrail',
FITR: 'Firetrail',
FLAT: 'Flat',
FOLLOW: 'Follow',
FOLW: 'Follow',
FORMATION: 'Formation',
FORM: 'Formation',
FRONT: 'Front',
FRNT: 'Front',
FRONTAGE: 'Frontage',
FRTG: 'Frontage',
FORESHORE: 'Foreshore',
FSHR: 'Foreshore',
'FIRE TRACK': 'Fire Track',
FTRK: 'Fire Track',
FOOTWAY: 'Footway',
FTWY: 'Footway',
FREEWAY: 'Freeway',
FRWY: 'Freeway',
FWY: 'Freeway',
GAP: 'Gap',
GARDEN: 'Garden',
GDN: 'Garden',
GARDENS: 'Gardens',
GDNS: 'Gardens',
GLADE: 'Glade',
GLD: 'Glade',
GLEN: 'Glen',
GULLY: 'Gully',
GLY: 'Gully',
GROVE: 'Grove',
GR: 'Grove',
GRV: 'Grove',
GV: 'Grove',
GVE: 'Grove',
GRANGE: 'Grange',
GRA: 'Grange',
GREEN: 'Green',
GRN: 'Green',
GROUND: 'Ground',
GRND: 'Ground',
GATE: 'Gate',
GTE: 'Gate',
GATES: 'Gates',
GTES: 'Gates',
HILL: 'Hill',
HIGHROAD: 'Highroad',
HRD: 'Highroad',
HEIGHTS: 'Heights',
HTS: 'Heights',
HIGHWAY: 'Highway',
HIGH: 'Highway',
HIGHW: 'Highway',
HIWAY: 'Highway',
HIWY: 'Highway',
HW: 'Highway',
HWAY: 'Highway',
HWY: 'Highway',
HY: 'Highway',
INTERCHANGE: 'Interchange',
INTG: 'Interchange',
INTERSECTION: 'Intersection',
INTN: 'Intersection',
JUNCTION: 'Junction',
JNC: 'Junction',
JNCT: 'Junction',
KEY: 'Key',
LANE: 'Lane',
LA: 'Lane',
LN: 'Lane',
LNE: 'Lane',
LANDING: 'Landing',
LDG: 'Landing',
LEES: 'Lees',
LINE: 'Line',
LINK: 'Link',
LOOKOUT: 'Lookout',
LKT: 'Lookout',
LANEWAY: 'Laneway',
LNWY: 'Laneway',
LOOP: 'Loop',
LITTLE: 'Little',
LT: 'Little',
LOWER: 'Lower',
LWR: 'Lower',
MALL: 'Mall',
MEW: 'Mew',
MW: 'Mew',
MEWS: 'Mews',
MWS: 'Mews',
MEANDER: 'Meander',
MNDR: 'Meander',
MOUNT: 'Mount',
MT: 'Mount',
MOTORWAY: 'Motorway',
MWY: 'Motorway',
NOOK: 'Nook',
OUTLOOK: 'Outlook',
OTLK: 'Outlook',
OUT: 'Outlook',
PARK: 'Park',
PART: 'Part',
PASS: 'Pass',
PATH: 'Path',
PARADE: 'Parade',
PAR: 'Parade',
PD: 'Parade',
PDE: 'Parade',
PATHWAY: 'Pathway',
PHWY: 'Pathway',
PWY: 'Pathway',
PIAZZA: 'Piazza',
PIAZ: 'Piazza',
PARKLANDS: 'Parklands',
PKLD: 'Parklands',
POCKET: 'Pocket',
PKT: 'Pocket',
PARKWAY: 'Parkway',
PKWY: 'Parkway',
PLACE: 'Place',
PL: 'Place',
PLC: 'Place',
PLATEAU: 'Plateau',
PLAT: 'Plateau',
PLAZA: 'Plaza',
PLZA: 'Plaza',
POINT: 'Point',
PNT: 'Point',
PORT: 'Port',
PROMENADE: 'Promenade',
PRM: 'Promenade',
PROM: 'Promenade',
PASSAGE: 'Passage',
PSGE: 'Passage',
QUADRANGLE: 'Quadrangle',
QDGL: 'Quadrangle',
QUADRANT: 'Quadrant',
QD: 'Quadrant',
QDRT: 'Quadrant',
QDT: 'Quadrant',
QUAD: 'Quad',
QUAY: 'Quay',
QY: 'Quay',
QUAYS: 'Quays',
QYS: 'Quays',
RAMP: 'Ramp',
REACH: 'Reach',
RCH: 'Reach',
ROAD: 'Road',
RAD: 'Road',
RD: 'Road',
RO: 'Road',
ROD: 'Road',
RIDGE: 'Ridge',
RDGE: 'Ridge',
ROADS: 'Roads',
RDS: 'Roads',
ROADSIDE: 'Roadside',
RDSD: 'Roadside',
ROADWAY: 'Roadway',
RDWY: 'Roadway',
RESERVE: 'Reserve',
RES: 'Reserve',
REST: 'Rest',
RIDGEWAY: 'Ridgeway',
RGWY: 'Ridgeway',
RIDE: 'Ride',
RING: 'Ring',
RISE: 'Rise',
RAMBLE: 'Ramble',
RAMB: 'Ramble',
RAMBL: 'Ramble',
RMBL: 'Ramble',
ROUND: 'Round',
RND: 'Round',
RONDE: 'Ronde',
RNDE: 'Ronde',
RANGE: 'Range',
RNGE: 'Range',
ROW: 'Row',
'RIGHT OF WAY': 'Right of Way',
ROWY: 'Right of Way',
ROSEBOWL: 'Rosebowl',
RSBL: 'Rosebowl',
ROUTE: 'Route',
RT: 'Route',
RTE: 'Route',
RETREAT: 'Retreat',
RTT: 'Retreat',
ROTARY: 'Rotary',
RTY: 'Rotary',
RUE: 'Rue',
RUN: 'Run',
RIVER: 'River',
RVR: 'River',
RIVIERA: 'Riviera',
RVRA: 'Riviera',
RIVERWAY: 'Riverway',
RVWY: 'Riverway',
SUBWAY: 'Subway',
SBWY: 'Subway',
SIDING: 'Siding',
SDNG: 'Siding',
'STATE HIGHWAY': 'State Highway',
SHWY: 'State Highway',
SLOPE: 'Slope',
SLPE: 'Slope',
SOUND: 'Sound',
SND: 'Sound',
SPUR: 'Spur',
SQUARE: 'Square',
SQ: 'Square',
STREET: 'Street',
ST: 'Street',
STR: 'Street',
STRT: 'Street',
STT: 'Street',
STEPS: 'Steps',
STPS: 'Steps',
STRAND: 'Strand',
STRA: 'Strand',
STRIP: 'Strip',
STRP: 'Strip',
STAIRS: 'Stairs',
STRS: 'Stairs',
'SERVICE WAY': 'Service Way',
SWY: 'Service Way',
TARN: 'Tarn',
TERRACE: 'Terrace',
TC: 'Terrace',
TCE: 'Terrace',
TER: 'Terrace',
TERC: 'Terrace',
TERCE: 'Terrace',
TERR: 'Terrace',
TRCE: 'Terrace',
THOROUGHFARE: 'Thoroughfare',
TFARE: 'Thoroughfare',
THOR: 'Thoroughfare',
TRUNKWAY: 'Trunkway',
TKWY: 'Trunkway',
TOLLWAY: 'Tollway',
TLWY: 'Tollway',
TOP: 'Top',
TOR: 'Tor',
TRIANGLE: 'Triangle',
TRI: 'Triangle',
TRACK: 'Track',
TRK: 'Track',
TRAIL: 'Trail',
TRL: 'Trail',
TRAILER: 'Trailer',
TRLR: 'Trailer',
TURN: 'Turn',
TOWERS: 'Towers',
TWRS: 'Towers',
UNDERPASS: 'Underpass',
UPAS: 'Underpass',
UPPER: 'Upper',
UPR: 'Upper',
VALE: 'Vale',
VA: 'Vale',
VIADUCT: 'Viaduct',
VDCT: 'Viaduct',
VIEW: 'View',
VILLAS: 'Villas',
VLLS: 'Villas',
VISTA: 'Vista',
VSTA: 'Vista',
WADE: 'Wade',
WALK: 'Walk',
WK: 'Walk',
WLK: 'Walk',
WAY: 'Way',
WHRF: 'Wharf',
WHARF: 'Wharf',
WALKWAY: 'Walkway',
WKWY: 'Walkway',
WYND: 'Wynd',
YARD: 'Yard',
};
